name: skill_core
description: "Final project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  go_router: ^16.0.0
  get_it: ^8.0.3
  firebase_analytics: ^11.5.2
  firebase_auth: ^5.6.2
  flutter_riverpod: ^2.6.1
  json_serializable: ^6.10.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  freezed: ^3.2.0
  cloud_firestore: ^5.6.12
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  mockito: ^5.5.0
  build_runner: ^2.7.0
  mocktail: ^1.0.4
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/logos/
  fonts:
    - family: LexandDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


flutter_native_splash:
  color: "#9438c7"
  android_12:
    image: assets/logos/logo_dark.png
    color: "#f6f2f3"
    image_dark: assets/logos/logo_dark.png
    color_dark: "#0b2136"
